### PR TITLE
Add basic HTML template

### LINKED ISSUE #2: Create a basic HTML template for playing with css

### PR DESCRIPTION
**Pull request by nittin-shankar**
It's having the most basic template which I want  to merge it to master.

Closes #2

### CODE REVIEW

**Comment by shankardevy** [comment]
Please mention which issue this PR is resolving.

**Comment by nittin-shankar** [comment]
Updated as requested

**Review by shankardevy — CHANGES_REQUESTED** [review]
Please add other important meta tags and include a CSS file in it.

**Comment by nittin-shankar** [comment]
added the three meta tags and please teach me how to include a css file

**Review by shankardevy — APPROVED** [review]

**Pull request merged**
